# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Lens_X_axis_rot:
    has_position_limits: true
    max_position: 0.698132
    min_position: -0.698132
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  Lens_X_axis_trans:
    has_position_limits: true
    max_position: 0.65
    min_position: 0
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  Lens_Y_axis_rot:
    has_position_limits: true
    max_position: 0.698132
    min_position: -0.698132
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  Lens_Y_axis_trans:
    has_position_limits: true
    max_position: 0.15
    min_position: -0.12
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  MainFrame_pitch:
    has_position_limits: true
    max_position: 0.523599
    min_position: -0.523599
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0