# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: lens_group
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Wheel_left_middle
    - Wheel_left_rear
    - Wheel_right_middle
    - Wheel_right_rear
    - MainFrame_pitch
    - Lens_Y_axis_trans
    - Lens_X_axis_trans
    - Lens_Y_axis_rot
    - Lens_X_axis_rot
    - Wheel_left_front
    - Wheel_right_front
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
controller_list:
  - name: lens_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - MainFrame_pitch
      - Lens_Y_axis_trans
      - Lens_X_axis_trans
      - Lens_Y_axis_rot
      - Lens_X_axis_rot